### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [AxonInteractive/bridge-server#1]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by DigitalMachinist** [comment]
I'll keep this in mind if I ever come back to this. This was written before ES6+ support was complete in Node (last commit was ~2.5 years ago and before the io.js hard-fork), so at the time it was a reasonable approach. However, I don't realistically expect to ever make this fix. There are far better frameworks/libraries to do what this package does nowadays.

Thanks for the tip.

**Comment by Drulac** [comment]
Ok I understand 😉
